-- MySQL Script generated by MySQL Workbench
-- Fri May 14 19:15:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_bd
-- -----------------------------------------------------
CREATE DATABASE projeto_bd;
USE projeto_bd;

-- -----------------------------------------------------
-- Table `projeto_bd`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`curso` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`curso` (
  `codigo_curso` VARCHAR(45) NOT NULL,
  `nome_curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`aluno` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`aluno` (
  `matricula_aluno` INT NOT NULL,
  `curso_aluno` INT NOT NULL,
  `tipo_aluno` INT NOT NULL,
  `status_aluno` INT NOT NULL,
  `curso_codigo_curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula_aluno`, `curso_codigo_curso`),
  INDEX `fk_aluno_curso1_idx` (`curso_codigo_curso` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_curso1`
    FOREIGN KEY (`curso_codigo_curso`)
    REFERENCES `projeto_bd`.`curso` (`codigo_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`professor` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`professor` (
  `id_professor` INT NOT NULL,
  `tipo_professor` INT NOT NULL,
  `area_pesquisa_professor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`usuario` ;

-- -----------------------------------------------------
-- Table `projeto_bd`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`disciplina` (
  `codigo_disciplina` VARCHAR(45) NOT NULL,
  `tipo_disciplina` INT NOT NULL,
  `nome_disciplina` VARCHAR(45) NOT NULL,
  `turma_disciplina` VARCHAR(45) NOT NULL,
  `carga_disciplina` INT NOT NULL,
  PRIMARY KEY (`codigo_disciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`divulgacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`divulgacao` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`divulgacao` (
  `codigo_divulgacao` INT NOT NULL,
  `titulo_divulgacao` VARCHAR(45) NOT NULL,
  `autor_divulgacao` VARCHAR(45) NOT NULL,
  `tipo_divulgacao` INT NOT NULL,
  `assunto_divulgacao` VARCHAR(255) NOT NULL,
  `professor_id_professor` INT NOT NULL,
  `aluno_matricula_aluno` INT NOT NULL,
  `aluno_curso_codigo_curso` VARCHAR(45) NOT NULL,
  `aluno_matricula_aluno1` INT NOT NULL,
  `aluno_curso_codigo_curso1` VARCHAR(45) NOT NULL,
  `professor_id_professor1` INT NOT NULL,
  PRIMARY KEY (`codigo_divulgacao`, `professor_id_professor`, `aluno_matricula_aluno`, `aluno_curso_codigo_curso`, `aluno_matricula_aluno1`, `aluno_curso_codigo_curso1`, `professor_id_professor1`),
  INDEX `fk_divulgacao_aluno1_idx` (`aluno_matricula_aluno1` ASC, `aluno_curso_codigo_curso1` ASC) VISIBLE,
  INDEX `fk_divulgacao_professor1_idx` (`professor_id_professor1` ASC) VISIBLE,
  CONSTRAINT `fk_divulgacao_aluno1`
    FOREIGN KEY (`aluno_matricula_aluno1` , `aluno_curso_codigo_curso1`)
    REFERENCES `mydb`.`aluno` (`matricula_aluno` , `curso_codigo_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_divulgacao_professor1`
    FOREIGN KEY (`professor_id_professor1`)
    REFERENCES `projeto_bd`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`voluntario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`voluntario` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`voluntario` (
  `id_voluntario` INT NOT NULL,
  `funcao_voluntario` VARCHAR(45) NOT NULL,
  `aluno_matricula_aluno` INT NOT NULL,
  `aluno_curso_codigo_curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_voluntario`),
  INDEX `fk_voluntario_aluno1_idx` (`aluno_matricula_aluno` ASC, `aluno_curso_codigo_curso` ASC) VISIBLE,
  CONSTRAINT `fk_voluntario_aluno1`
    FOREIGN KEY (`aluno_matricula_aluno` , `aluno_curso_codigo_curso`)
    REFERENCES `projeto_bd`.`aluno` (`matricula_aluno` , `curso_codigo_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`tutoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`tutoria` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`tutoria` (
  `codigo_tutoria` INT NOT NULL,
  `data_hora_tutoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_tutoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`duvida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`duvida` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`duvida` (
  `codigo_duvida` INT NOT NULL,
  `tipo_duvida` VARCHAR(45) NOT NULL,
  `status_duvida` INT NOT NULL,
  PRIMARY KEY (`codigo_duvida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`projeto` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`projeto` (
  `codigo_projeto` INT NOT NULL,
  `status_projeto` INT NOT NULL,
  `participantes_projeto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_projeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_has_disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`aluno_has_disciplina` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`aluno_has_disciplina` (
  `aluno_matricula_aluno` INT NOT NULL,
  `aluno_curso_codigo_curso` VARCHAR(45) NOT NULL,
  `disciplina_codigo_disciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aluno_matricula_aluno`, `aluno_curso_codigo_curso`, `disciplina_codigo_disciplina`),
  INDEX `fk_aluno_has_disciplina_disciplina1_idx` (`disciplina_codigo_disciplina` ASC) VISIBLE,
  INDEX `fk_aluno_has_disciplina_aluno1_idx` (`aluno_matricula_aluno` ASC, `aluno_curso_codigo_curso` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_disciplina_aluno1`
    FOREIGN KEY (`aluno_matricula_aluno` , `aluno_curso_codigo_curso`)
    REFERENCES `projeto_bd`.`aluno` (`matricula_aluno` , `curso_codigo_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_codigo_disciplina`)
    REFERENCES `projeto_bd`.`disciplina` (`codigo_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`professor_has_disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`professor_has_disciplina` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`professor_has_disciplina` (
  `professor_id_professor` INT NOT NULL,
  `disciplina_codigo_disciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`professor_id_professor`, `disciplina_codigo_disciplina`),
  INDEX `fk_professor_has_disciplina_disciplina1_idx` (`disciplina_codigo_disciplina` ASC) VISIBLE,
  INDEX `fk_professor_has_disciplina_professor1_idx` (`professor_id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_professor_has_disciplina_professor1`
    FOREIGN KEY (`professor_id_professor`)
    REFERENCES `projeto_bd`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_codigo_disciplina`)
    REFERENCES `projeto_bd`.`disciplina` (`codigo_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`divulgacao_has_projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`divulgacao_has_projeto` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`divulgacao_has_projeto` (
  `divulgacao_codigo_divulgacao` INT NOT NULL,
  `divulgacao_professor_id_professor` INT NOT NULL,
  `divulgacao_aluno_matricula_aluno` INT NOT NULL,
  `divulgacao_aluno_curso_codigo_curso` VARCHAR(45) NOT NULL,
  `divulgacao_aluno_matricula_aluno1` INT NOT NULL,
  `divulgacao_aluno_curso_codigo_curso1` VARCHAR(45) NOT NULL,
  `divulgacao_professor_id_professor1` INT NOT NULL,
  `projeto_codigo_projeto` INT NOT NULL,
  PRIMARY KEY (`divulgacao_codigo_divulgacao`, `divulgacao_professor_id_professor`, `divulgacao_aluno_matricula_aluno`, `divulgacao_aluno_curso_codigo_curso`, `divulgacao_aluno_matricula_aluno1`, `divulgacao_aluno_curso_codigo_curso1`, `divulgacao_professor_id_professor1`, `projeto_codigo_projeto`),
  INDEX `fk_divulgacao_has_projeto_projeto1_idx` (`projeto_codigo_projeto` ASC) VISIBLE,
  INDEX `fk_divulgacao_has_projeto_divulgacao1_idx` (`divulgacao_codigo_divulgacao` ASC, `divulgacao_professor_id_professor` ASC, `divulgacao_aluno_matricula_aluno` ASC, `divulgacao_aluno_curso_codigo_curso` ASC, `divulgacao_aluno_matricula_aluno1` ASC, `divulgacao_aluno_curso_codigo_curso1` ASC, `divulgacao_professor_id_professor1` ASC) VISIBLE,
  CONSTRAINT `fk_divulgacao_has_projeto_divulgacao1`
    FOREIGN KEY (`divulgacao_codigo_divulgacao` , `divulgacao_professor_id_professor` , `divulgacao_aluno_matricula_aluno` , `divulgacao_aluno_curso_codigo_curso` , `divulgacao_aluno_matricula_aluno1` , `divulgacao_aluno_curso_codigo_curso1` , `divulgacao_professor_id_professor1`)
    REFERENCES `projeto_bd`.`divulgacao` (`codigo_divulgacao` , `professor_id_professor` , `aluno_matricula_aluno` , `aluno_curso_codigo_curso` , `aluno_matricula_aluno1` , `aluno_curso_codigo_curso1` , `professor_id_professor1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_divulgacao_has_projeto_projeto1`
    FOREIGN KEY (`projeto_codigo_projeto`)
    REFERENCES `mydb`.`projeto` (`codigo_projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`divulgacao_has_duvida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`divulgacao_has_duvida` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`divulgacao_has_duvida` (
  `divulgacao_codigo_divulgacao` INT NOT NULL,
  `divulgacao_professor_id_professor` INT NOT NULL,
  `divulgacao_aluno_matricula_aluno` INT NOT NULL,
  `divulgacao_aluno_curso_codigo_curso` VARCHAR(45) NOT NULL,
  `divulgacao_aluno_matricula_aluno1` INT NOT NULL,
  `divulgacao_aluno_curso_codigo_curso1` VARCHAR(45) NOT NULL,
  `divulgacao_professor_id_professor1` INT NOT NULL,
  `duvida_codigo_duvida` INT NOT NULL,
  PRIMARY KEY (`divulgacao_codigo_divulgacao`, `divulgacao_professor_id_professor`, `divulgacao_aluno_matricula_aluno`, `divulgacao_aluno_curso_codigo_curso`, `divulgacao_aluno_matricula_aluno1`, `divulgacao_aluno_curso_codigo_curso1`, `divulgacao_professor_id_professor1`, `duvida_codigo_duvida`),
  INDEX `fk_divulgacao_has_duvida_duvida1_idx` (`duvida_codigo_duvida` ASC) VISIBLE,
  INDEX `fk_divulgacao_has_duvida_divulgacao1_idx` (`divulgacao_codigo_divulgacao` ASC, `divulgacao_professor_id_professor` ASC, `divulgacao_aluno_matricula_aluno` ASC, `divulgacao_aluno_curso_codigo_curso` ASC, `divulgacao_aluno_matricula_aluno1` ASC, `divulgacao_aluno_curso_codigo_curso1` ASC, `divulgacao_professor_id_professor1` ASC) VISIBLE,
  CONSTRAINT `fk_divulgacao_has_duvida_divulgacao1`
    FOREIGN KEY (`divulgacao_codigo_divulgacao` , `divulgacao_professor_id_professor` , `divulgacao_aluno_matricula_aluno` , `divulgacao_aluno_curso_codigo_curso` , `divulgacao_aluno_matricula_aluno1` , `divulgacao_aluno_curso_codigo_curso1` , `divulgacao_professor_id_professor1`)
    REFERENCES `projeto_bd`.`divulgacao` (`codigo_divulgacao` , `professor_id_professor` , `aluno_matricula_aluno` , `aluno_curso_codigo_curso` , `aluno_matricula_aluno1` , `aluno_curso_codigo_curso1` , `professor_id_professor1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_divulgacao_has_duvida_duvida1`
    FOREIGN KEY (`duvida_codigo_duvida`)
    REFERENCES `mydb`.`duvida` (`codigo_duvida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`divulgacao_has_tutoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`divulgacao_has_tutoria` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`divulgacao_has_tutoria` (
  `divulgacao_codigo_divulgacao` INT NOT NULL,
  `divulgacao_professor_id_professor` INT NOT NULL,
  `divulgacao_aluno_matricula_aluno` INT NOT NULL,
  `divulgacao_aluno_curso_codigo_curso` VARCHAR(45) NOT NULL,
  `divulgacao_aluno_matricula_aluno1` INT NOT NULL,
  `divulgacao_aluno_curso_codigo_curso1` VARCHAR(45) NOT NULL,
  `divulgacao_professor_id_professor1` INT NOT NULL,
  `tutoria_codigo_tutoria` INT NOT NULL,
  PRIMARY KEY (`divulgacao_codigo_divulgacao`, `divulgacao_professor_id_professor`, `divulgacao_aluno_matricula_aluno`, `divulgacao_aluno_curso_codigo_curso`, `divulgacao_aluno_matricula_aluno1`, `divulgacao_aluno_curso_codigo_curso1`, `divulgacao_professor_id_professor1`, `tutoria_codigo_tutoria`),
  INDEX `fk_divulgacao_has_tutoria_tutoria1_idx` (`tutoria_codigo_tutoria` ASC) VISIBLE,
  INDEX `fk_divulgacao_has_tutoria_divulgacao1_idx` (`divulgacao_codigo_divulgacao` ASC, `divulgacao_professor_id_professor` ASC, `divulgacao_aluno_matricula_aluno` ASC, `divulgacao_aluno_curso_codigo_curso` ASC, `divulgacao_aluno_matricula_aluno1` ASC, `divulgacao_aluno_curso_codigo_curso1` ASC, `divulgacao_professor_id_professor1` ASC) VISIBLE,
  CONSTRAINT `fk_divulgacao_has_tutoria_divulgacao1`
    FOREIGN KEY (`divulgacao_codigo_divulgacao` , `divulgacao_professor_id_professor` , `divulgacao_aluno_matricula_aluno` , `divulgacao_aluno_curso_codigo_curso` , `divulgacao_aluno_matricula_aluno1` , `divulgacao_aluno_curso_codigo_curso1` , `divulgacao_professor_id_professor1`)
    REFERENCES `projeto_bd`.`divulgacao` (`codigo_divulgacao` , `professor_id_professor` , `aluno_matricula_aluno` , `aluno_curso_codigo_curso` , `aluno_matricula_aluno1` , `aluno_curso_codigo_curso1` , `professor_id_professor1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_divulgacao_has_tutoria_tutoria1`
    FOREIGN KEY (`tutoria_codigo_tutoria`)
    REFERENCES `projeto_bd`.`tutoria` (`codigo_tutoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_bd`.`aluno_has_tutoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto_bd`.`aluno_has_tutoria` ;

CREATE TABLE IF NOT EXISTS `projeto_bd`.`aluno_has_tutoria` (
  `aluno_matricula_aluno` INT NOT NULL,
  `aluno_curso_codigo_curso` VARCHAR(45) NOT NULL,
  `tutoria_codigo_tutoria` INT NOT NULL,
  PRIMARY KEY (`aluno_matricula_aluno`, `aluno_curso_codigo_curso`, `tutoria_codigo_tutoria`),
  INDEX `fk_aluno_has_tutoria_tutoria1_idx` (`tutoria_codigo_tutoria` ASC) VISIBLE,
  INDEX `fk_aluno_has_tutoria_aluno1_idx` (`aluno_matricula_aluno` ASC, `aluno_curso_codigo_curso` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_tutoria_aluno1`
    FOREIGN KEY (`aluno_matricula_aluno` , `aluno_curso_codigo_curso`)
    REFERENCES `projeto_bd`.`aluno` (`matricula_aluno` , `curso_codigo_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_tutoria_tutoria1`
    FOREIGN KEY (`tutoria_codigo_tutoria`)
    REFERENCES `projeto_bd`.`tutoria` (`codigo_tutoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
