# Generated by Django 3.2.3 on 2021-05-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Carros',
        ),
    ]
