# Generated by Django 3.2.3 on 2021-05-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210514_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
