# Generated by Django 3.2.3 on 2021-05-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuarios_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
